Updated source, authors and haswell benchmark values
cryptoeng/pqdb pull request #179
Opened 2020-11-03 10:46 UTC by TomerHawk

It would be possible to add 5 more parameter Sets, which are also implemented and submitted in round 3 .

2020-11-09 12:48 UTC, benj-zen requested changes
Looks good. Just the one comment.

2020-11-09 12:48 UTC, benj-zen commented on encryption/classic-mceliece/classic-mceliece.yaml
> +  - 'Martin Tomlinson,'
copy paste error

2020-11-09 13:24 UTC, benj-zen commented
I'd also add the new parameter sets.

2020-11-10 14:08 UTC, TomerHawk commented
> I'd also add the new parameter sets.

Okay, I will add them

2020-11-13 12:27 UTC, benj-zen approved these changes

2020-11-13 12:27 UTC, merged