Update Falcon
cryptoeng/pqdb pull request #187
Opened 2020-11-10 14:03 UTC by TomerHawk

Updated avx2 benchmarks

2020-11-13 13:05 UTC, benj-zen requested changes
Numbers look good. Something went wrong with the memory requirements.

2020-11-13 14:17 UTC, TomerHawk commented on signatures/falcon/falcon/bench/avx2_1024_skylake.yaml
> +  enc|sign: !<tag:yaml.org,2002:js/undefined> ''
seems like I saved their an empty string with the enter-helper. Enter-helper doesn't show any problem in this field, so I didn't notice :)

2020-11-20 10:12 UTC, benj-zen commented on signatures/falcon/falcon/bench/avx2_1024_skylake.yaml
> +  enc|sign: !<tag:yaml.org,2002:js/undefined> ''
We may need to adjust the JSON-Scheme.

2020-11-30 10:42 UTC, benj-zen approved these changes

2020-11-30 10:42 UTC, merged