Update rainbow
cryptoeng/pqdb pull request #189
Opened 2020-11-13 08:58 UTC by TomerHawk

2020-11-13 12:54 UTC, benj-zen requested changes
I think you mixed up the key sizes and some of the benchmarks for the parameter sets. The table captions are below the tables in the paper.

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-standard/impl/avx2.yaml
> +  - ''
empty item

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-standard/bench/avx2_V_haswell.yaml
> +  comment: ''
empty comment

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-standard/bench/avx2_I_haswell.yaml
> +  comment: ''
empty comment

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-standard/bench/avx2_III_haswell.yaml
> +  comment: ''
empty comment

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-cz/impl/avx2.yaml
> +  - ''
empty item

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-cz/bench/avx2_I_haswell.yaml
> +  comment: ''
empty comment

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-cz/bench/avx2_III_haswell.yaml
> +  comment: ''
empty comment

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-compressed/impl/avx2.yaml
> +  - ''
empty item

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-compressed/bench/avx2_I_haswell.yaml
> +  comment: ''
empty comment

2020-11-13 12:54 UTC, benj-zen commented on signatures/rainbow/rainbow-compressed/bench/avx2_III_haswell.yaml
> +  comment: ''
empty comment

2020-11-13 13:58 UTC, TomerHawk commented
> I think you mixed up the key sizes and some of the benchmarks for the parameter sets. The table captions are below the tables in the paper.

Ah, I see. That makes a lot more sense

2020-11-20 11:46 UTC, benj-zen approved these changes

2020-11-20 11:46 UTC, merged